name: "1. Python"

on: push

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./app/Dockerfile"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rotoku/sts-python

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            rotoku/sts-python:${{ github.sha }}
            rotoku/sts-python:v0.0.1
            rotoku/sts-python:latest
          labels: ${{ steps.meta.outputs.labels }}
